#!/bin/bash

# Activate virtual environment
source ./venv/Scripts/activate

# Run the Python application using the virtual environment's Python
./venv/Scripts/python . "$@"

# Deactivate virtual environment (optional)
deactivate